name: "Build / Test"

on:
  pull_request:
  push:
    branches:
      - jq-*

jobs:
  build-test:

    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            cc: gcc
          - os: ubuntu-latest
            cc: clang
          - os: macos-latest
            cc: clang

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.cc }} automake autoconf libtool

    - name: Install dependencies (MacOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install autoconf automake libtool

    - name: Build
      run: |
        autoreconf -i
        ./configure \
          --with-oniguruma=builtin \
          --disable-maintainer-mode \
          --enable-static \
          --enable-all-static \
          CC=${{ matrix.cc }}
        make -j"$(nproc)"

    - name: Run smoke test
      run: ./jq --version

    - name: Run testsuite
      run: make check
